### ISSUE TITLE
Arithmetic Syntax Error in entrypoint.sh When No Version Tag Exists

### ISSUE THREAD

**Issue by nicholas-fedor** [nicholas-fedor/go-proxy-pull-action#6]
## Summary

The `entrypoint.sh` script in the `go-proxy-pull-action` fails with an "arithmetic syntax error" when the workflow is triggered in a context where no version tag (e.g., `v1.0.0`) exists. This happens because the script does not handle cases where the `VERSION` or `MAJOR_VERSION` variables are empty or non-numeric, leading to a failure in the arithmetic comparison on line 17.

## Steps to Reproduce

1.     Create a GitHub repository with a Go module (e.g., `github.com/example/my-module`).
2.     Set up a GitHub Actions workflow that uses nicholas-fedor/go-proxy-pull-action (e.g., at commit `2c0cd90fca4f4c81efcc530ee6435752a261aea9`).
3.     Configure the workflow to trigger on a push to the `main` branch (not on a tag push), ensuring no version tag exists in the repository.
4.     Run the workflow and observe the error in the `go-proxy-pull-action step`.

## Example workflow configuration

```yaml
name: Test Workflow

on:
  push:
    branches:
      - main

jobs:
  renew-docs:
    name: Refresh pkg.go.dev
    runs-on: ubuntu-latest
    steps:
      - name: Pull new module version
        uses: nicholas-fedor/go-proxy-pull-action@2c0cd90fca4f4c81efcc530ee6435752a261aea9
        with:
          goproxy: https://proxy.golang.org
          import_path: github.com/example/my-module
```

## Expected Behavior

The action fails with the following error:

```text
/entrypoint.sh: line 17: arithmetic syntax error
```

This error occurs because the `MAJOR_VERSION` variable, derived from `VERSION`, is empty or non-numeric when no tag is present, causing the arithmetic comparison `$((10#${MAJOR_VERSION})) -gt 1` to fail.

## Relevant Code

The issue is in the `entrypoint.sh script`, specifically at line 17:

```bash
readonly MAJOR_VERSION="$(printf '%s' "$VERSION" | cut -d '.' -f 1 | sed 's/v//g')"
if [ $((10#${MAJOR_VERSION})) -gt 1 ]; then
  PACKAGE="$PACKAGE/v$MAJOR_VERSION"
fi
```

When `GITHUB_REF` is `refs/heads/main` (instead of `refs/tags/vX.Y.Z`), `TAG` and `VERSION` are set to `main`, making `MAJOR_VERSION` an empty string or non-numeric, which causes the arithmetic error.
